// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTxV-cYFmVuJUZOyO5-1jTyzPDpcUC0sA',
    appId: '1:588475945530:ios:1b56a2911ebc595be9db03',
    messagingSenderId: '588475945530',
    projectId: 'portfolio-211b6',
    storageBucket: 'portfolio-211b6.appspot.com',
    iosBundleId: 'com.example.porfoilio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTxV-cYFmVuJUZOyO5-1jTyzPDpcUC0sA',
    appId: '1:588475945530:ios:1b56a2911ebc595be9db03',
    messagingSenderId: '588475945530',
    projectId: 'portfolio-211b6',
    storageBucket: 'portfolio-211b6.appspot.com',
    iosBundleId: 'com.example.porfoilio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1-r6Q9eJvWYhbh6_497UHn6de0yiVXN8',
    appId: '1:588475945530:web:aabb3b4f2b84732fe9db03',
    messagingSenderId: '588475945530',
    projectId: 'portfolio-211b6',
    authDomain: 'portfolio-211b6.firebaseapp.com',
    storageBucket: 'portfolio-211b6.appspot.com',
    measurementId: 'G-RCNYDD112J',
  );

  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-r6Q9eJvWYhbh6_497UHn6de0yiVXN8',
    appId: '1:588475945530:web:97b2182013da7343e9db03',
    messagingSenderId: '588475945530',
    projectId: 'portfolio-211b6',
    authDomain: 'portfolio-211b6.firebaseapp.com',
    storageBucket: 'portfolio-211b6.appspot.com',
    measurementId: 'G-XJK5ZNL5FZ',
  );

}